### ISSUE TITLE
Arrays within Structs

### ISSUE THREAD

**Issue by derekzx** [vyperlang/vyper#1200]
### Version Information

* vyper Version: 0.1.0b6
* OS: Ubuntu 18.04
* Python Version (python --version): 3.6.7

### What's your issue about?
Returning an array within a struct throws error.

I know that structs are currently in Alpha phase but this bug may be helpful when designing tests!

Input
```
Compilation: vyper test.py
```

Output:
```
Error compiling:  test.py
Traceback (most recent call last):
  File "/usr/local/bin/vyper", line 4, in <module>
    __import__('pkg_resources').run_script('vyper==0.1.0b6', 'vyper')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/vyper-0.1.0b6-py3.6.egg/EGG-INFO/scripts/vyper", line 85, in <module>
  File "/usr/local/lib/python3.6/dist-packages/vyper-0.1.0b6-py3.6.egg/vyper/compiler.py", line 108, in compile_codes
  File "/usr/local/lib/python3.6/dist-packages/vyper-0.1.0b6-py3.6.egg/EGG-INFO/scripts/vyper", line 51, in exc_handler
  File "/usr/local/lib/python3.6/dist-packages/vyper-0.1.0b6-py3.6.egg/vyper/compiler.py", line 105, in compile_codes
  File "/usr/local/lib/python3.6/dist-packages/vyper-0.1.0b6-py3.6.egg/vyper/compiler.py", line 87, in <lambda>
  File "/usr/local/lib/python3.6/dist-packages/vyper-0.1.0b6-py3.6.egg/vyper/compiler.py", line 8, in __compile
  File "/usr/local/lib/python3.6/dist-packages/vyper-0.1.0b6-py3.6.egg/vyper/parser/parser.py", line 259, in parse_tree_to_lll
  File "/usr/local/lib/python3.6/dist-packages/vyper-0.1.0b6-py3.6.egg/vyper/parser/parser.py", line 207, in parse_other_functions
  File "/usr/local/lib/python3.6/dist-packages/vyper-0.1.0b6-py3.6.egg/vyper/parser/parser.py", line 571, in parse_func
  File "/usr/local/lib/python3.6/dist-packages/vyper-0.1.0b6-py3.6.egg/vyper/parser/parser.py", line 571, in <listcomp>
  File "/usr/local/lib/python3.6/dist-packages/vyper-0.1.0b6-py3.6.egg/vyper/parser/parser.py", line 588, in parse_body
  File "/usr/local/lib/python3.6/dist-packages/vyper-0.1.0b6-py3.6.egg/vyper/parser/parser.py", line 603, in parse_stmt
  File "/usr/local/lib/python3.6/dist-packages/vyper-0.1.0b6-py3.6.egg/vyper/parser/stmt.py", line 80, in __init__
  File "/usr/local/lib/python3.6/dist-packages/vyper-0.1.0b6-py3.6.egg/vyper/parser/stmt.py", line 626, in parse_return
  File "/usr/local/lib/python3.6/dist-packages/vyper-0.1.0b6-py3.6.egg/vyper/parser/parser_utils.py", line 668, in gen_tuple_return
vyper.exceptions.TypeMismatchException: line 69: Can't return type int128[2] as part of tuple
    return G2Point({
----^
```
Full Code:
```
struct G2Point:
    X : int128[2]
    Y : int128[2]

@public
def test() -> G2Point:
    return G2Point({
        X : [1,2],
        Y : [2,3]
    })

```

### How can it be fixed?

Fill this in if you know how to fix it.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/17759758/51226260-9e62cd80-1989-11e9-8f8a-88b793406b25.png)

**Comment by derekzx** [comment]
#1019

**Comment by charles-cooper** [comment]
Since structs and tuples have the same representation I think this and https://github.com/ethereum/vyper/issues/955 should be solved with the same implementation.

**Comment by charles-cooper** [comment]
This is fixed in master (I think as of https://github.com/vyperlang/vyper/pull/1723).
