### ISSUE TITLE
Private functions does not support argument as an empty byte array

### ISSUE THREAD

**Issue by SAYONG** [vyperlang/vyper#1539]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b11+commit.595d183
* OS: Linux 4.19.49-1-MANJARO
* Python Version (output of `python --version`): 3.73
* Environment (output of `pip freeze`):
```
appdirs==1.4.3
atomicwrites==1.3.0
attrdict==2.0.1
attrs==19.1.0
backcall==0.1.0
base58==1.0.3
black==19.3b0
cached-property==1.5.1
certifi==2019.6.16
chardet==3.0.4
Click==7.0
cytoolz==0.10.0
decorator==4.4.0
eth-abi==2.0.0
eth-account==0.4.0
eth-bloom==1.0.3
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.1.2
eth-tester==0.2.0b2
eth-typing==2.1.0
eth-utils==1.6.1
hexbytes==0.2.0
idna==2.8
importlib-metadata==0.18
ipdb==0.12
ipfshttpclient==0.4.12
ipython==7.6.1
ipython-genutils==0.2.0
jedi==0.14.1
jsonschema==2.6.0
lru-dict==1.1.6
more-itertools==7.2.0
multiaddr==0.0.8
mypy-extensions==0.4.1
netaddr==0.7.19
packaging==19.0
parsimonious==0.8.1
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
pluggy==0.12.0
plyvel==1.1.0
prompt-toolkit==2.0.9
protobuf==3.9.0
ptyprocess==0.6.0
py==1.8.0
py-ecc==1.7.1
py-evm==0.3.0a1
pycryptodome==3.8.2
pyethash==0.1.27
Pygments==2.4.2
pyparsing==2.4.1
pytest==5.0.1
python-dateutil==2.8.0
requests==2.22.0
rlp==1.1.0
semantic-version==2.6.0
six==1.12.0
toml==0.10.0
toolz==0.10.0
traitlets==4.3.2
trie==1.4.0
urllib3==1.25.3
varint==1.0.2
vyper==0.1.0b11
wcwidth==0.1.7
web3==5.0.0b4
websockets==7.0
zipp==0.5.2
```
### What's your issue about?

I've created a private function with fixed byte array as a parameter, but every time I passing an empty byte array to the function then it will cause stack underflow error.

Contract `store.vy`:
```python
storage: bytes[10]

@private
def store(_bytes: bytes[10]):
    self.storage = _bytes

@public
def proxyStore(_bytes: bytes[10]):
    self.store(_bytes)
```

Test script
```python
from eth_tester import EthereumTester
from web3 import Web3
from web3.providers.eth_tester import EthereumTesterProvider
from vyper import compiler


w3 = Web3(EthereumTesterProvider(EthereumTester()))
w3.eth.defaultAccount = w3.eth.accounts[0]
owner = w3.eth.accounts[0]

with open("contracts/store.vy") as f:
    source_code = f.read()

compiled_contract = compiler.compile_code(source_code, ["abi", "bytecode"])

contract_address = deploy(w3, compiled_contract)

contract = w3.eth.contract(address=contract_address, abi=compiled_contract["abi"])
contract.functions.proxyStore(b'').transact({'from':owner})
```

Returns:
I've tested with 2 backends `eth-tester` and `ganache-cli`

With `eth-tester` returns:
```
*** eth.exceptions.InsufficientStack: ('Wanted 1 stack item, only had %d', 0)
```

With `ganache-cli` returns:
```
*** ValueError: {'message': 'VM Exception while processing transaction: stack underflow', 'code': -32000, 'data': {'0x69740217236fcfe0ab885379675e47a52030989fee21b03c2470038f30f69448': {'error': 'stack underflow', 'program_counter': 576, 'return': '0x'}, 'stack': 'o: VM Exception while processing transaction: stack underflow\n    at Function.o.fromResults (/app/ganache-core.docker.cli.js:10:82299)\n    at /app/ganache-core.docker.cli.js:47:151756\n    at /app/ganache-core.docker.cli.js:47:128087\n    at b (/app/ganache-core.docker.cli.js:47:127744)\n    at /app/ganache-core.docker.cli.js:47:127797\n    at t.default (/app/ganache-core.docker.cli.js:52:259867)\n    at /app/ganache-core.docker.cli.js:47:128711\n    at _.n.emit (/app/ganache-core.docker.cli.js:61:1063005)\n    at /app/ganache-core.docker.cli.js:61:1701802\n    at /app/ganache-core.docker.cli.js:61:1701825\n    at /app/ganache-core.docker.cli.js:61:351481\n    at /app/ganache-core.docker.cli.js:2:69007\n    at i (/app/ganache-core.docker.cli.js:2:84062)\n    at /app/ganache-core.docker.cli.js:2:64530\n    at process._tickCallback (internal/process/next_tick.js:61:11)', 'name': 'o'}}
```

But this problem not happen when I change the function to be public function.
```python
@public
def store(_bytes: bytes[10]):
    self.storage = _bytes
```

**Comment by charles-cooper** [comment]
@SAYONG I think this was resolved in master which was just released as beta-11. Can you try again against that?

**Comment by SAYONG** [comment]
Beta-11 is not working for me :(
Still got the same error.

**Comment by fubuloubu** [comment]
Seems to work just fine, closing. @SAYONG please re-open if you have the same problem
