### ISSUE TITLE
truffle cannot compile vyper contract

### ISSUE THREAD

**Issue by acheron2302** [vyperlang/vyper#1798]
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b14+commit.4ac5ef5
* OS: linux
* Python Version (output of `python --version`): 3.7.5
* Environment (output of `pip freeze`): 
```
apipkg==1.5
asttokens==2.0.3
attrdict==2.0.1
attrs==19.3.0
base58==1.0.3
blake2b-py==0.1.3
cached-property==1.5.1
certifi==2019.11.28
chardet==3.0.4
coverage==5.0.1
coveralls==1.10.0
cytoolz==0.10.1
docopt==0.6.2
entrypoints==0.3
eth-abi==2.1.0
eth-account==0.4.0
eth-bloom==1.0.3
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.1.2
eth-tester==0.3.0b1
eth-typing==2.2.1
eth-utils==1.8.4
execnet==1.7.1
filelock==3.0.12
flake8==3.7.9
flake8-bugbear==19.8.0
flake8-use-fstring==1.0
hexbytes==0.2.0
hypothesis==4.57.1
idna==2.8
importlib-metadata==1.3.0
ipfshttpclient==0.4.12
isort==4.3.21
jsonschema==3.2.0
lark-parser==0.7.8
lru-dict==1.1.6
mccabe==0.6.1
more-itertools==8.0.2
multiaddr==0.0.9
mypy==0.761
mypy-extensions==0.4.3
netaddr==0.7.19
packaging==19.2
parsimonious==0.8.1
pluggy==0.13.1
protobuf==3.11.2
py==1.8.1
py-ecc==1.7.1
py-evm==0.3.0a8
pycodestyle==2.5.0
pycryptodome==3.9.4
pyethash==0.1.27
pyflakes==2.1.1
pyparsing==2.4.6
pyrsistent==0.15.6
pysha3==1.0.2
pytest==5.3.2
pytest-cov==2.8.1
pytest-forked==1.1.3
pytest-xdist==1.31.0
PyYAML==5.2
requests==2.22.0
rlp==1.2.0
semantic-version==2.8.4
six==1.13.0
sortedcontainers==2.1.0
toml==0.10.0
toolz==0.10.0
tox==3.14.3
trie==1.4.0
typed-ast==1.4.0
typing-extensions==3.7.4.1
urllib3==1.25.7
varint==1.0.2
virtualenv==16.7.9
vyper==0.1.0b14
wcwidth==0.1.8
web3==5.2.2
websockets==7.0
zipp==0.6.0
```

### What's your issue about?
I run the command: `truffle compile` in my truffle folder but i get this error:
```
Compiling your contracts...
===========================
> Compiling ./contracts/ERC20.vy
Error: KeyError: '/home/haxerl/project/vyper_ERC20/contracts/ERC20.vy'

Compilation of /home/haxerl/project/vyper_ERC20/contracts/ERC20.vy failed. See above.
    at Object.compile (/usr/local/lib/node_modules/truffle/build/webpack:/packages/workflow-compile/legacy/index.js:80:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.1.6 (core: 5.1.6)
Node v10.17.0
(vyper-venv)
```

**Comment by fubuloubu** [comment]
Might be better off in Truffle's repository? @gnidan

**Comment by gnidan** [comment]
Please open an issue on Truffle's side!
