### ISSUE TITLE
Constructor can't use another internal function

### ISSUE THREAD

**Issue by tacitvenom** [vyperlang/vyper#2528]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.0
* OS: osx
* Python Version (output of `python --version`): 3.9.7

### What's your issue about?
Unable to use an internal function in constructor irrespective of its position in the vyper contract
Please include information like:

* full output of the error you received

```
$> vyper contracts/Example1.vy
Error compiling: contracts/Example1.vy
vyper.exceptions.FunctionDeclarationException: Function does not exist or has not been declared yet (reminder: functions cannot call functions later in code than themselves): _setExampleState

$> vyper contracts/Example2.vy
Error compiling: contracts/Example2.vy
vyper.exceptions.FunctionDeclarationException: Function does not exist or has not been declared yet (reminder: functions cannot call functions later in code than themselves): _setExampleState
```
* what command you ran
`vyper <contract>`
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
```
# @version 0.3.0

## Example1.vy
exampleState: public(uint256)  # should be positive

@external
def __init__(
    exampleState: uint256
):
    self._setExampleState(exampleState)

@internal
def _setExampleState(exampleState: uint256):
    assert exampleState > 0
    self.exampleState = exampleState
```

and 
```
# @version 0.3.0

## Example2.vy
exampleState: public(uint256)  # should be positive


@internal
def _setExampleState(exampleState: uint256):
    assert exampleState > 0
    self.exampleState = exampleState


@external
def __init__(
    exampleState: uint256
):
    self._setExampleState(exampleState)

```
* please try running your example with the --debug flag turned on
```
$> vyper --debug contracts/Example2.vy
Error compiling: contracts/Example2.vy
Traceback (most recent call last):
  File "/Users/user/anaconda/envs/tmp/bin/vyper", line 8, in <module>
    sys.exit(_parse_cli_args())
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/cli/vyper_compile.py", line 55, in _parse_cli_args
    return _parse_args(sys.argv[1:])
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/cli/vyper_compile.py", line 143, in _parse_args
    compiled = compile_files(
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/cli/vyper_compile.py", line 253, in compile_files
    compiler_data = vyper.compile_codes(
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/evm/opcodes.py", line 223, in _wrapper
    return fn(*args, **kwargs)
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/compiler/__init__.py", line 110, in compile_codes
    exc_handler(contract_name, exc)
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/cli/vyper_compile.py", line 177, in exc_handler
    raise exception
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/compiler/__init__.py", line 107, in compile_codes
    out[contract_name][output_format] = OUTPUT_FORMATS[output_format](compiler_data)
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/compiler/output.py", line 178, in build_bytecode_output
    return f"0x{compiler_data.bytecode.hex()}"
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/compiler/phases.py", line 146, in bytecode
    self._bytecode = generate_bytecode(self.assembly)
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/compiler/phases.py", line 134, in assembly
    self._assembly = generate_assembly(self.lll_nodes, self.use_ovm)
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/compiler/phases.py", line 122, in lll_nodes
    self._gen_lll()
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/compiler/phases.py", line 117, in _gen_lll
    self._lll_nodes, self._lll_runtime = generate_lll_nodes(self.global_ctx, self.use_ovm)
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/compiler/phases.py", line 252, in generate_lll_nodes
    lll_nodes, lll_runtime = parser.parse_tree_to_lll(global_ctx)
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/old_codegen/parser.py", line 220, in parse_tree_to_lll
    init_func_lll, _frame_start, _frame_size = generate_lll_for_function(
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/old_codegen/function_definitions/common.py", line 88, in generate_lll_for_function
    _, context = _run_pass(memory_allocator=None)
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/old_codegen/function_definitions/common.py", line 85, in _run_pass
    o = generate_lll_for_external_function(code, sig, context, check_nonpayable)
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/old_codegen/function_definitions/external_function.py", line 194, in generate_lll_for_external_function
    body = [parse_body(c, context) for c in code.body]
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/old_codegen/function_definitions/external_function.py", line 194, in <listcomp>
    body = [parse_body(c, context) for c in code.body]
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/old_codegen/stmt.py", line 425, in parse_body
    return parse_stmt(code, context)
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/old_codegen/stmt.py", line 419, in parse_stmt
    return Stmt(stmt, context).lll_node
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/old_codegen/stmt.py", line 34, in __init__
    self.lll_node = fn()
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/old_codegen/stmt.py", line 40, in parse_Expr
    return Stmt(self.stmt.value, self.context).lll_node
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/old_codegen/stmt.py", line 34, in __init__
    self.lll_node = fn()
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/old_codegen/stmt.py", line 141, in parse_Call
    return self_call.lll_for_self_call(self.stmt, self.context)
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/old_codegen/self_call.py", line 35, in lll_for_self_call
    sig, kw_vals = context.lookup_internal_function(method_name, pos_args_lll)
  File "/Users/user/anaconda/envs/tmp/lib/python3.9/site-packages/vyper/old_codegen/context.py", line 234, in lookup_internal_function
    raise FunctionDeclarationException(
vyper.exceptions.FunctionDeclarationException: Function does not exist or has not been declared yet (reminder: functions cannot call functions later in code than themselves): _setExampleState

```

**Comment by fubuloubu** [comment]
dup of https://github.com/vyperlang/vyper/issues/1631
