### ISSUE TITLE
AttributeError: 'AddressDefinition' object has no attribute 'position'

### ISSUE THREAD

**Issue by adapt7** [vyperlang/vyper#2954]
### Version Information

* vyper Version (output of `vyper --version`): 0.1+commit.573d77f7
* OS: linux
* Python Version (output of `python --version`): 3.9

### What's your issue about?

Code compilation works fine via terminal but fails via vyper-serve and Remix IDE. It throws this error:

```Exception occurred during processing of request from ('127.0.0.1', 54782)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.9/http/server.py", line 425, in handle
    self.handle_one_request()
  File "/usr/lib/python3.9/http/server.py", line 413, in handle_one_request
    method()
  File ".local/lib/python3.9/site-packages/vyper/cli/vyper_serve.py", line 73, in do_POST
    response, status_code = self._compile(data)
  File ".local/lib/python3.9/site-packages/vyper/cli/vyper_serve.py", line 95, in _compile
    out_dict = vyper.compile_codes(
  File ".local/lib/python3.9/site-packages/vyper/evm/opcodes.py", line 223, in _wrapper
    return fn(*args, **kwargs)
  File ".local/lib/python3.9/site-packages/vyper/compiler/__init__.py", line 138, in compile_codes
    raise exc
  File ".local/lib/python3.9/site-packages/vyper/compiler/__init__.py", line 133, in compile_codes
    out[contract_name][output_format] = OUTPUT_FORMATS[output_format](compiler_data)
  File ".local/lib/python3.9/site-packages/vyper/compiler/output.py", line 79, in build_ir_output
    return compiler_data.ir_nodes
  File ".local/lib/python3.9/site-packages/vyper/compiler/phases.py", line 122, in ir_nodes
    ir, ir_runtime, sigs = self._ir_output
  File "/usr/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File ".local/lib/python3.9/site-packages/vyper/compiler/phases.py", line 118, in _ir_output
    return generate_ir_nodes(self.global_ctx, self.no_optimize)
  File ".local/lib/python3.9/site-packages/vyper/compiler/phases.py", line 260, in generate_ir_nodes
    ir_nodes, ir_runtime, function_sigs = module.generate_ir_for_module(global_ctx)
  File ".local/lib/python3.9/site-packages/vyper/codegen/module.py", line 209, in generate_ir_for_module
    runtime, internal_functions = _runtime_ir(runtime_functions, all_sigs, global_ctx)
  File ".local/lib/python3.9/site-packages/vyper/codegen/module.py", line 138, in _runtime_ir
    func_ir = generate_ir_for_function(func_ast, all_sigs, global_ctx, False)
  File ".local/lib/python3.9/site-packages/vyper/codegen/function_definitions/common.py", line 62, in generate_ir_for_function
    o = generate_ir_for_external_function(code, sig, context, skip_nonpayable_check)
  File ".local/lib/python3.9/site-packages/vyper/codegen/function_definitions/external_function.py", line 186, in generate_ir_for_external_function
    body += [parse_body(code.body, context, ensure_terminated=True)]
  File ".local/lib/python3.9/site-packages/vyper/codegen/stmt.py", line 424, in parse_body
    ir = parse_stmt(stmt, context)
  File ".local/lib/python3.9/site-packages/vyper/codegen/stmt.py", line 398, in parse_stmt
    return Stmt(stmt, context).ir_node
  File ".local/lib/python3.9/site-packages/vyper/codegen/stmt.py", line 40, in __init__
    self.ir_node = fn()
  File ".local/lib/python3.9/site-packages/vyper/codegen/stmt.py", line 217, in parse_Assert
    test_expr = Expr.parse_value_expr(self.stmt.test, self.context)
  File ".local/lib/python3.9/site-packages/vyper/codegen/expr.py", line 682, in parse_value_expr
    return unwrap_location(cls(expr, context).ir_node)
  File ".local/lib/python3.9/site-packages/vyper/codegen/expr.py", line 74, in __init__
    self.ir_node = fn()
  File ".local/lib/python3.9/site-packages/vyper/codegen/expr.py", line 458, in parse_Compare
    left = Expr.parse_value_expr(self.expr.left, self.context)
  File ".local/lib/python3.9/site-packages/vyper/codegen/expr.py", line 682, in parse_value_expr
    return unwrap_location(cls(expr, context).ir_node)
  File ".local/lib/python3.9/site-packages/vyper/codegen/expr.py", line 74, in __init__
    self.ir_node = fn()
  File ".local/lib/python3.9/site-packages/vyper/codegen/expr.py", line 263, in parse_Attribute
    type_.position.position,
AttributeError: 'AddressDefinition' object has no attribute 'position'```

**Comment by charles-cooper** [comment]
how are you running vyper-serve and what is the version (output of `vyper-serve --version`)?

**Comment by adapt7** [comment]
vyper-serve --version
`0.1+commit573d77f7`

Run command: `vyper-serve -b localhost:8001`

**Comment by charles-cooper** [comment]
wow, interesting! can you give the code or a repro which is producing the error?

**Comment by adapt7** [comment]
I simplified the code to this:

```@external
@payable
def destroy():
	selfdestruct(msg.sender)

@external
@payable
def __default__():
	pass

@external
@payable
def __init__():
	pass
```

and getting error:

```Exception occurred during processing of request from ('127.0.0.1', 52996)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.9/http/server.py", line 425, in handle
    self.handle_one_request()
  File "/usr/lib/python3.9/http/server.py", line 413, in handle_one_request
    method()
  File ".local/lib/python3.9/site-packages/vyper/cli/vyper_serve.py", line 79, in do_POST
    self.wfile.write(json.dumps(response).encode())
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type IRnode is not JSON serializable
----------------------------------------

**Comment by ChaituKReddy** [comment]
Having the same issue with `0.3.7+commit.6020b8b` version of `vyper-serve`. Works fine in terminal but errors out when tried to compile from remix.
