### ISSUE TITLE
unable to use vyper-serve 0.3.6

### ISSUE THREAD

**Issue by yann300** [vyperlang/vyper#3075]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.6
* OS: ubutu
* Python Version 3.8

### What's your issue about?

unable to use the vyper-serve api endpoint, the call always fail with an error:
`Unable to json serialize IRNode`

**Comment by ronev** [comment]
I have the same problem on macOs with 0.3.7 version:
```
127.0.0.1 - - [06/Apr/2023 11:13:00] "POST /compile HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 62889)
Traceback (most recent call last):
  File "/Users/ronev/.pyenv/versions/3.10.10/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/ronev/.pyenv/versions/3.10.10/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/ronev/.pyenv/versions/3.10.10/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/Users/ronev/.pyenv/versions/3.10.10/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/Users/ronev/.pyenv/versions/3.10.10/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/Users/ronev/.local/pipx/venvs/vyper/lib/python3.10/site-packages/vyper/cli/vyper_serve.py", line 79, in do_POST
    self.wfile.write(json.dumps(response).encode())
  File "/Users/ronev/.pyenv/versions/3.10.10/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Users/ronev/.pyenv/versions/3.10.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/ronev/.pyenv/versions/3.10.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/ronev/.pyenv/versions/3.10.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type IRnode is not JSON serializable
```
