### ISSUE TITLE
Calls to functions with higher mutability not prevented

### ISSUE THREAD

**Issue by trocher** [vyperlang/vyper#3161]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.8+commit.6020b8bb
* OS: OSX
* Python Version (output of `python --version`): 3.8.0

### What's your issue about?

When a `pure` (respectively `view`) function tries to call a function with a higher mutability, the compiler should fail. This is well enforced when such call is embedded directly in a `Expr` statement (the return value is not used). However when the call is not directly a statement, the compiler behave differently:

1. For a `pure` function calling a `view` function, the second case will compile successfully. For example here, while `ContractB` will fail to compile due to a `StateAccessViolation` (`Cannot call non-pure function from a pure function`),  `ContractA` will compile successfully although `test`, a `pure` function is calling a `view` function.

`ContractA`:
``` Vyper
interface A:
    def bar() -> uint16: view
@external
@pure
def test(to:address):
    a:A = A(to)
    x:uint16 = a.bar()
```
`ContractB`:
``` Vyper
interface A:
    def bar() -> uint16: view
@external
@pure
def test(to:address):
    a:A = A(to)
    a.bar()
```

2. For a `pure` or a `view` function calling a `nonpayable` or a `payable` function, the second case will fail to compile with an assertion error. For example here, while `ContractD` will fail to compile due to a `StateAccessViolation` (`Cannot call a mutating function from a view function`),  `ContractC` will fail as well with the given assertion error.

`ContractC`:
``` Vyper
interface A:
    def bar() -> uint16: nonpayable
@external
@view
def test(to:address):
    a:A = A(to)
    x:uint16 = a.bar()
```
`ContractD`:
``` Vyper
interface A:
    def bar() -> uint16: nonpayable
@external
@view
def test(to:address):
    a:A = A(to)
    a.bar()
```
Output of compiling `ContractC`:
```
Error compiling: tests/customs/code.vy
Traceback (most recent call last):
  File "/Users/trocher/Documents/thesis/vyper/venv/bin/vyper", line 11, in <module>
    load_entry_point('vyper==0.3.8', 'console_scripts', 'vyper')()
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 57, in _parse_cli_args
    return _parse_args(sys.argv[1:])
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 154, in _parse_args
    compiled = compile_files(
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 294, in compile_files
    compiler_data = vyper.compile_codes(
  File "/Users/trocher/Documents/thesis/vyper/vyper/evm/opcodes.py", line 226, in _wrapper
    return fn(*args, **kwargs)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/__init__.py", line 141, in compile_codes
    exc_handler(contract_name, exc)
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 189, in exc_handler
    raise exception
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/__init__.py", line 138, in compile_codes
    out[contract_name][output_format] = OUTPUT_FORMATS[output_format](compiler_data)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/output.py", line 79, in build_ir_output
    return compiler_data.ir_nodes
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/phases.py", line 126, in ir_nodes
    ir, ir_runtime, sigs = self._ir_output
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/functools.py", line 966, in __get__
    val = self.func(instance)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/phases.py", line 122, in _ir_output
    return generate_ir_nodes(self.global_ctx, self.no_optimize)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/phases.py", line 279, in generate_ir_nodes
    ir_nodes, ir_runtime, function_sigs = module.generate_ir_for_module(global_ctx)
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/module.py", line 209, in generate_ir_for_module
    runtime, internal_functions = _runtime_ir(runtime_functions, all_sigs, global_ctx)
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/module.py", line 145, in _runtime_ir
    func_ir = generate_ir_for_function(func_ast, all_sigs, global_ctx, skip_nonpayable_check)
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/function_definitions/common.py", line 62, in generate_ir_for_function
    o = generate_ir_for_external_function(code, sig, context, skip_nonpayable_check)
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/function_definitions/external_function.py", line 182, in generate_ir_for_external_function
    body += [parse_body(code.body, context, ensure_terminated=True)]
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/stmt.py", line 424, in parse_body
    ir = parse_stmt(stmt, context)
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/stmt.py", line 398, in parse_stmt
    return Stmt(stmt, context).ir_node
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/stmt.py", line 40, in __init__
    self.ir_node = fn()
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/stmt.py", line 68, in parse_AnnAssign
    sub = Expr(self.stmt.value, self.context).ir_node
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/expr.py", line 75, in __init__
    self.ir_node = fn()
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/expr.py", line 682, in parse_Call
    return external_call.ir_for_external_call(self.expr, self.context)
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/external_call.py", line 241, in ir_for_external_call
    _external_call_helper(contract_address, args_ir, call_kwargs, call_expr, context)
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/external_call.py", line 214, in _external_call_helper
    assert use_staticcall, "typechecker missed this"
```
### How can it be fixed?

My guess is that the issue comes from the fact that the semantics validation performed in `visit_Expr` are not performed for calls that are not directly in `Expr` AST nodes. 
https://github.com/vyperlang/vyper/blob/6020b8bbf66b062d299d87bc7e4eddc4c9d1c157/vyper/semantics/validation/local.py#L472-L511

**Comment by trocher** [comment]
For completeness, adding to this issue that calling a method attached to a type that have a return value (To my knowledge the only one currently is `DynArray.pop()`) in a `view` function leads to the same behavior:
```Vyper
a:DynArray[uint16,3]
@external
def __init__():
    self.a = [1,2,3]
@view
@external
def bar()->DynArray[uint16,3]:
    x:uint16 = self.a.pop()
    return self.a # return [1,2]
```
