### ISSUE TITLE
`raise UNREACHABLE` leads to `CompilerPanic`

### ISSUE THREAD

**Issue by trocher** [vyperlang/vyper#3169]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.8+commit.6020b8bb
* OS: OSX
* Python Version (output of `python --version`): 3.8.0

### What's your issue about?

When setting the reason string of an exception to `UNREACHABLE` to use the `INVALID` opcode instead of `REVERT`, the compiler panic as shown in the example below.

```Bash
vyper -f ast,ir --verbose tests/customs/code.vy
```
```Vyper
@external
def foo():
    raise UNREACHABLE
```
```Bash
Error compiling: tests/customs/code.vy
Traceback (most recent call last):
  File "/Users/trocher/Documents/thesis/vyper/venv/bin/vyper", line 11, in <module>
    load_entry_point('vyper==0.3.8', 'console_scripts', 'vyper')()
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 57, in _parse_cli_args
    return _parse_args(sys.argv[1:])
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 154, in _parse_args
    compiled = compile_files(
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 294, in compile_files
    compiler_data = vyper.compile_codes(
  File "/Users/trocher/Documents/thesis/vyper/vyper/evm/opcodes.py", line 226, in _wrapper
    return fn(*args, **kwargs)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/__init__.py", line 141, in compile_codes
    exc_handler(contract_name, exc)
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 189, in exc_handler
    raise exception
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/__init__.py", line 138, in compile_codes
    out[contract_name][output_format] = OUTPUT_FORMATS[output_format](compiler_data)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/output.py", line 79, in build_ir_output
    return compiler_data.ir_nodes
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/phases.py", line 126, in ir_nodes
    ir, ir_runtime, sigs = self._ir_output
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/functools.py", line 966, in __get__
    val = self.func(instance)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/phases.py", line 122, in _ir_output
    return generate_ir_nodes(self.global_ctx, self.no_optimize)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/phases.py", line 279, in generate_ir_nodes
    ir_nodes, ir_runtime, function_sigs = module.generate_ir_for_module(global_ctx)
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/module.py", line 209, in generate_ir_for_module
    runtime, internal_functions = _runtime_ir(runtime_functions, all_sigs, global_ctx)
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/module.py", line 145, in _runtime_ir
    func_ir = generate_ir_for_function(func_ast, all_sigs, global_ctx, skip_nonpayable_check)
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/function_definitions/common.py", line 62, in generate_ir_for_function
    o = generate_ir_for_external_function(code, sig, context, skip_nonpayable_check)
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/function_definitions/external_function.py", line 182, in generate_ir_for_external_function
    body += [parse_body(code.body, context, ensure_terminated=True)]
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/stmt.py", line 424, in parse_body
    ir = parse_stmt(stmt, context)
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/stmt.py", line 398, in parse_stmt
    return Stmt(stmt, context).ir_node
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/stmt.py", line 40, in __init__
    self.ir_node = fn()
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/stmt.py", line 226, in parse_Raise
    return self._assert_reason(None, self.stmt.exc)
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/stmt.py", line 163, in _assert_reason
    return IRnode.from_list(
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/ir_node.py", line 538, in from_list
    [cls.from_list(o, source_pos=source_pos) for o in obj[1:]],
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/ir_node.py", line 538, in <listcomp>
    [cls.from_list(o, source_pos=source_pos) for o in obj[1:]],
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/ir_node.py", line 523, in from_list
    return cls(
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/ir_node.py", line 144, in __init__
    _check(self.value is not None, "None is not allowed as IRnode value")
  File "/Users/trocher/Documents/thesis/vyper/vyper/codegen/ir_node.py", line 142, in _check
    raise CompilerPanic(str(err))
vyper.exceptions.CompilerPanic: None is not allowed as IRnode value

This is an unhandled internal compiler error. Please create an issue on Github to notify the developers.
https://github.com/vyperlang/vyper/issues/new?template=bug.md
```

**Comment by trocher** [comment]
As a side note, `UNREACHABLE` is not a reserved keyword, hence, for a programmer or user who is not familiar with the `UNREACHABLE` custom semantic, it might be confusing that in the following contract, a call to `bar` will revert with `invalid opcode` and not `this is unreachable`.
```Vyper
@external
def bar():
    UNREACHABLE: String[20] = "this is unreachable"
    assert 3>2, UNREACHABLE
```

**Comment by fubuloubu** [comment]
> As a side note, `UNREACHABLE` is not a reserved keyword, hence, for a programmer or user who is not familiar with the `UNREACHABLE` custom semantic, it might be confusing that in the following contract, a call to `bar` will revert with `invalid opcode` and not `this is unreachable`.
> 
> ```vyper
> @external
> def bar():
>     UNREACHABLE: String[20] = "this is unreachable"
>     x: uint256 = 3
>     assert 2>x, UNREACHABLE
> ```

This is a great find. Probably a separate issue though?

**Comment by trocher** [comment]
> > As a side note, `UNREACHABLE` is not a reserved keyword, hence, for a programmer or user who is not familiar with the `UNREACHABLE` custom semantic, it might be confusing that in the following contract, a call to `bar` will revert with `invalid opcode` and not `this is unreachable`.
> > ```vyper
> > @external
> > def bar():
> >     UNREACHABLE: String[20] = "this is unreachable"
> >     x: uint256 = 3
> >     assert 2>x, UNREACHABLE
> > ```
> 
> This is a great find. Probably a separate issue though?

Separated it in a new issue: https://github.com/vyperlang/vyper/issues/3171!

**Comment by charles-cooper** [comment]
looks like a dup of https://github.com/vyperlang/vyper/issues/3070 -- please reopen if i am mistaken
