### ISSUE TITLE
Dynamics Arrays of `Enum` are no longer allowed

### ISSUE THREAD

**Issue by trocher** [vyperlang/vyper#3193]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.8+commit.1cd6f3db
* OS: OSX
* Python Version (output of `python --version`): 3.8.0

### What's your issue about?

In `v0.3.7`, Static Arrays of Enums were not allowed but Dynamics arrays could contain `Enum` types.
However, Dynamics Arrays of `Enum` are no longer allowed after #3156. 
```Vyper
enum Foo:
    a
bar: DynArray[Foo, 10]
```
Result of compilation with commit 1cd6f3db (with `v0.3.7`, it would compile succesfully) :

```Bash
Traceback (most recent call last):
  File "/Users/trocher/Documents/thesis/vyper/venv/bin/vyper", line 11, in <module>
    load_entry_point('vyper==0.3.8', 'console_scripts', 'vyper')()
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 57, in _parse_cli_args
    return _parse_args(sys.argv[1:])
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 154, in _parse_args
    compiled = compile_files(
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 294, in compile_files
    compiler_data = vyper.compile_codes(
  File "/Users/trocher/Documents/thesis/vyper/vyper/evm/opcodes.py", line 226, in _wrapper
    return fn(*args, **kwargs)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/__init__.py", line 141, in compile_codes
    exc_handler(contract_name, exc)
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 189, in exc_handler
    raise exception
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/__init__.py", line 138, in compile_codes
    out[contract_name][output_format] = OUTPUT_FORMATS[output_format](compiler_data)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/output.py", line 82, in build_ir_output
    return compiler_data.ir_nodes
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/phases.py", line 126, in ir_nodes
    ir, ir_runtime, sigs = self._ir_output
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/functools.py", line 966, in __get__
    val = self.func(instance)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/phases.py", line 122, in _ir_output
    return generate_ir_nodes(self.global_ctx, self.no_optimize)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/phases.py", line 117, in global_ctx
    return generate_global_context(self.vyper_module_folded, self.interface_codes)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/phases.py", line 107, in vyper_module_folded
    module, storage_layout = self._folded_module
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/functools.py", line 966, in __get__
    val = self.func(instance)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/phases.py", line 101, in _folded_module
    return generate_folded_ast(
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/phases.py", line 229, in generate_folded_ast
    validate_semantics(vyper_module_folded, interface_codes)
  File "/Users/trocher/Documents/thesis/vyper/vyper/semantics/analysis/__init__.py", line 12, in validate_semantics
    add_module_namespace(vyper_ast, interface_codes)
  File "/Users/trocher/Documents/thesis/vyper/vyper/semantics/analysis/module.py", line 43, in add_module_namespace
    ModuleNodeVisitor(vy_module, interface_codes, namespace)
  File "/Users/trocher/Documents/thesis/vyper/vyper/semantics/analysis/module.py", line 88, in __init__
    err_list.raise_if_not_empty()
  File "/Users/trocher/Documents/thesis/vyper/vyper/exceptions.py", line 18, in raise_if_not_empty
    raise self[0]
  File "/Users/trocher/Documents/thesis/vyper/vyper/semantics/analysis/module.py", line 76, in __init__
    self.visit(node)
  File "/Users/trocher/Documents/thesis/vyper/vyper/semantics/analysis/common.py", line 20, in visit
    visitor_fn(node, *args)
  File "/Users/trocher/Documents/thesis/vyper/vyper/semantics/analysis/module.py", line 186, in visit_VariableDecl
    type_ = type_from_annotation(node.annotation)
  File "/Users/trocher/Documents/thesis/vyper/vyper/semantics/types/utils.py", line 99, in type_from_annotation
    return type_ctor.from_annotation(node)
  File "/Users/trocher/Documents/thesis/vyper/vyper/semantics/types/subscriptable.py", line 266, in from_annotation
    raise StructureException(f"Arrays of {value_type} are not allowed", node)
vyper.exceptions.StructureException: Arrays of enum Foo('a') are not allowed
  contract "tests/customs/code.vy:5", line 5:5 
       4     a
  ---> 5 bar: DynArray[Foo, 10]
  ------------^
       6
```
### How can it be fixed?

If the intention is to keep the v0.3.7 semantics, my guess would be to implement a similar carveout as the one done for arrays of bytestrings since `Enum` does not have the `_as_array` field.
https://github.com/vyperlang/vyper/blob/1cd6f3db7e06ed97ffd9eefb9cfc67506e461544/vyper/semantics/types/bytestrings.py#L29-L31

**Comment by charles-cooper** [comment]
should we allow static arrays of enums though?

**Comment by trocher** [comment]
> should we allow static arrays of enums though?

It would be a good idea imo as it would be consistent with the other 1-word representable types
