### ISSUE TITLE
Collisions between IR identifiers possible.

### ISSUE THREAD

**Issue by trocher** [vyperlang/vyper#3226]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.8+commit.ae7d6d28
* OS: OSX
* Python Version (output of `python --version`): 3.8.0

### What's your issue about?

IR identifiers for functions in the IR are the result of the concatenation using `_` of the visibility, the name and the types of the arguments. Using the fact that `_` is allowed both in function names and in types names, it is possible to create collisions between labels.

```Vyper
interface _uint256:
    def a():nonpayable

@internal
def foo(a:_uint256):
    pass

@internal
def foo_(a:uint256):
    pass
```
```Vyper
Error compiling: tests/customs/code.vy
Traceback (most recent call last):
  File "/Users/trocher/Documents/thesis/vyper/venv/bin/vyper", line 11, in <module>
    load_entry_point('vyper==0.3.8', 'console_scripts', 'vyper')()
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 57, in _parse_cli_args
    return _parse_args(sys.argv[1:])
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 154, in _parse_args
    compiled = compile_files(
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 294, in compile_files
    compiler_data = vyper.compile_codes(
  File "/Users/trocher/Documents/thesis/vyper/vyper/evm/opcodes.py", line 226, in _wrapper
    return fn(*args, **kwargs)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/__init__.py", line 141, in compile_codes
    exc_handler(contract_name, exc)
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 189, in exc_handler
    raise exception
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/__init__.py", line 138, in compile_codes
    out[contract_name][output_format] = OUTPUT_FORMATS[output_format](compiler_data)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/output.py", line 248, in build_bytecode_output
    return f"0x{compiler_data.bytecode.hex()}"
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/functools.py", line 966, in __get__
    val = self.func(instance)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/phases.py", line 150, in bytecode
    self.assembly, is_runtime=False, no_bytecode_metadata=self.no_bytecode_metadata
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/functools.py", line 966, in __get__
    val = self.func(instance)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/phases.py", line 141, in assembly
    return generate_assembly(self.ir_nodes, self.no_optimize)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/phases.py", line 279, in generate_assembly
    assembly = compile_ir.compile_to_assembly(ir_nodes, no_optimize=no_optimize)
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 189, in apply_line_no_wrapper
    ret = func(*args, **kwargs)
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 211, in compile_to_assembly
    res = _compile_to_assembly(code)
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 189, in apply_line_no_wrapper
    ret = func(*args, **kwargs)
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 502, in _compile_to_assembly
    subcode = _compile_to_assembly(ir)
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 189, in apply_line_no_wrapper
    ret = func(*args, **kwargs)
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 535, in _compile_to_assembly
    o.extend(_compile_to_assembly(arg, withargs, existing_labels, break_dest, height))
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 189, in apply_line_no_wrapper
    ret = func(*args, **kwargs)
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 535, in _compile_to_assembly
    o.extend(_compile_to_assembly(arg, withargs, existing_labels, break_dest, height))
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 189, in apply_line_no_wrapper
    ret = func(*args, **kwargs)
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 684, in _compile_to_assembly
    raise Exception(f"Label with name {label_name} already exists!")
Exception: Label with name internal_foo___uint256_ already exists!
```

**Comment by kenn2chill0917-star** [comment]
Error compiling: tests/customs/code.vy
Traceback (most recent call last):
  File "/Users/trocher/Documents/thesis/vyper/venv/bin/vyper", line 11, in <module>
    load_entry_point('vyper==0.3.8', 'console_scripts', 'vyper')()
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 57, in _parse_cli_args
    return _parse_args(sys.argv[1:])
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 154, in _parse_args
    compiled = compile_files(
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 294, in compile_files
    compiler_data = vyper.compile_codes(
  File "/Users/trocher/Documents/thesis/vyper/vyper/evm/opcodes.py", line 226, in _wrapper
    return fn(*args, **kwargs)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/__init__.py", line 141, in compile_codes
    exc_handler(contract_name, exc)
  File "/Users/trocher/Documents/thesis/vyper/vyper/cli/vyper_compile.py", line 189, in exc_handler
    raise exception
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/__init__.py", line 138, in compile_codes
    out[contract_name][output_format] = OUTPUT_FORMATS[output_format](compiler_data)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/output.py", line 248, in build_bytecode_output
    return f"0x{compiler_data.bytecode.hex()}"
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/functools.py", line 966, in __get__
    val = self.func(instance)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/phases.py", line 150, in bytecode
    self.assembly, is_runtime=False, no_bytecode_metadata=self.no_bytecode_metadata
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/functools.py", line 966, in __get__
    val = self.func(instance)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/phases.py", line 141, in assembly
    return generate_assembly(self.ir_nodes, self.no_optimize)
  File "/Users/trocher/Documents/thesis/vyper/vyper/compiler/phases.py", line 279, in generate_assembly
    assembly = compile_ir.compile_to_assembly(ir_nodes, no_optimize=no_optimize)
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 189, in apply_line_no_wrapper
    ret = func(*args, **kwargs)
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 211, in compile_to_assembly
    res = _compile_to_assembly(code)
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 189, in apply_line_no_wrapper
    ret = func(*args, **kwargs)
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 502, in _compile_to_assembly
    subcode = _compile_to_assembly(ir)
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 189, in apply_line_no_wrapper
    ret = func(*args, **kwargs)
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 535, in _compile_to_assembly
    o.extend(_compile_to_assembly(arg, withargs, existing_labels, break_dest, height))
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 189, in apply_line_no_wrapper
    ret = func(*args, **kwargs)
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 535, in _compile_to_assembly
    o.extend(_compile_to_assembly(arg, withargs, existing_labels, break_dest, height))
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 189, in apply_line_no_wrapper
    ret = func(*args, **kwargs)
  File "/Users/trocher/Documents/thesis/vyper/vyper/ir/compile_ir.py", line 684, in _compile_to_assembly
    raise Exception(f"Label with name {label_name} already exists!")
Exception: Label with name internal_foo___uint256_ already exists!Duplicate of #4977
