### ISSUE TITLE
AssertionError while compiling

### ISSUE THREAD

**Issue by xrchz** [vyperlang/vyper#3290]
### Version Information

* vyper Version (output of `vyper --version`): `0.3.7+commit.6020b8b`
* OS: GNU/Linux
* Python Version (output of `python --version`): `Python 3.10.9`

### What's your issue about?
```
> vyper error3.vy
Error compiling: error3.vy
AssertionError
```
```
> vyper error3.vy --verbose
Error compiling: error3.vy
Traceback (most recent call last):
  File "/home/ramana/.local/share/virtualenvs/vyper-xO0-3u-e/bin/vyper", line 8, in <module>
    sys.exit(_parse_cli_args())
  File "/home/ramana/.local/share/virtualenvs/vyper-xO0-3u-e/lib/python3.10/site-packages/vyper/cli/vyper_compile.py", line 57, in _parse_cli_args
    return _parse_args(sys.argv[1:])
  File "/home/ramana/.local/share/virtualenvs/vyper-xO0-3u-e/lib/python3.10/site-packages/vyper/cli/vyper_compile.py", line 154, in _parse_args
    compiled = compile_files(
  File "/home/ramana/.local/share/virtualenvs/vyper-xO0-3u-e/lib/python3.10/site-packages/vyper/cli/vyper_compile.py", line 294, in compile_files
    compiler_data = vyper.compile_codes(
  File "/home/ramana/.local/share/virtualenvs/vyper-xO0-3u-e/lib/python3.10/site-packages/vyper/evm/opcodes.py", line 226, in _wrapper
    return fn(*args, **kwargs)
  File "/home/ramana/.local/share/virtualenvs/vyper-xO0-3u-e/lib/python3.10/site-packages/vyper/compiler/__init__.py", line 141, in compile_codes
    exc_handler(contract_name, exc)
  File "/home/ramana/.local/share/virtualenvs/vyper-xO0-3u-e/lib/python3.10/site-packages/vyper/cli/vyper_compile.py", line 189, in exc_handler
    raise exception
  File "/home/ramana/.local/share/virtualenvs/vyper-xO0-3u-e/lib/python3.10/site-packages/vyper/compiler/__init__.py", line 138, in compile_codes
    out[contract_name][output_format] = OUTPUT_FORMATS[output_format](compiler_data)
  File "/home/ramana/.local/share/virtualenvs/vyper-xO0-3u-e/lib/python3.10/site-packages/vyper/compiler/output.py", line 245, in build_bytecode_output
    return f"0x{compiler_data.bytecode.hex()}"
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/ramana/.local/share/virtualenvs/vyper-xO0-3u-e/lib/python3.10/site-packages/vyper/compiler/phases.py", line 149, in bytecode
    return generate_bytecode(
  File "/home/ramana/.local/share/virtualenvs/vyper-xO0-3u-e/lib/python3.10/site-packages/vyper/compiler/phases.py", line 334, in generate_bytecode
    return compile_ir.assembly_to_evm(
  File "/home/ramana/.local/share/virtualenvs/vyper-xO0-3u-e/lib/python3.10/site-packages/vyper/ir/compile_ir.py", line 1124, in assembly_to_evm
    bytecode, _ = assembly_to_evm(PUSH_N(symbol_map[item], n=CODE_OFST_SIZE))
  File "/home/ramana/.local/share/virtualenvs/vyper-xO0-3u-e/lib/python3.10/site-packages/vyper/ir/compile_ir.py", line 37, in PUSH_N
    assert x == 0
AssertionError
```
```
> cat error3.vy | curl -F 'f:1=<-' ix.io
http://ix.io/4ona
```

**Comment by charles-cooper** [comment]
this no longer produces an error on master (e8b5b3c2f53e6417f98e215225b544c4c50615e2)
