### ISSUE TITLE
Internal Compiler Error When Compiling Oracle

### ISSUE THREAD

**Issue by ControlCplusControlV** [vyperlang/vyper#3691]
### Version Information

* vyper Version (output of `vyper --version`): 0.3.10+commit.9136169
* OS: osx
* Python Version (output of `python --version`): Python 3.11.6

### What's your issue about?

```
# @version 0.3.10

interface IOracle:
  def get() -> (bool, uint256): nonpayable
  def peek() -> (bool, uint256): view
  def peekSpot() -> uint256: view

interface AmbientOracle:
  def queryPrice(base: address, quote: address, poolIdx: uint256) -> uint128: nonpayable

lens: public(immutable(address))
token0: public(immutable(address))
token1: public(immutable(address))
priceToken: public(immutable(address))

wad: constant(uint256) = 10 ** 18

last_price: public(uint256)

@external
def __init__(_lens: address, tokenA: address, tokenB: address, _priceToken: address):
  lens = _lens
  priceToken = _priceToken

  _token0: address = empty(address)
  _token1: address = empty(address)
  if convert(convert(tokenA, bytes32), uint256) > convert(convert(tokenB, bytes32), uint256):
    _token0 = tokenA
    _token1 = tokenB
  else:
    _token0 = tokenB
    _token1 = tokenA
  token0 = _token0
  token1 = _token1

@view
@internal
def calculate_price() -> uint256:
  average_price: uint256 = convert(AmbientOracle(lens).queryPrice(token0, token1, 420), uint256)
  full_price: uint256 = self.mul_div(average_price, average_price, 2**64, False)
  normalized_price: uint256 = self.mul_div(full_price, wad, 2**64, False)

  if token1 == priceToken:
    return (1 * normalized_price) * wad
  else:
    return ((wad * wad) / normalized_price) / wad

@external
def get() -> (bool, uint256):
  new_price: uint256 = self.calculate_price()
  if new_price != self.last_price:
    self.last_price = new_price
    return (True, new_price)
  else:
    # Out of caution return new_price anyway, and save an SLOAD
    # We did check they are equal implicitly as well
    return (False, new_price)

@view
@external
def peek() -> (bool, uint256):
  new_price: uint256 = self.calculate_price()
  if new_price != self.last_price:
    return (True, new_price)
  else:
    # Out of caution return new_price anyway, and save an SLOAD
    # We did check they are equal implicitly as well
    return (False, new_price)

@view
@external
def peekSpot() -> uint256:
  return self.calculate_price()


@internal
@pure
def mul_div(x: uint256, y: uint256, denominator: uint256, roundup: bool) -> uint256:
    """
    @dev Calculates "(x * y) / denominator" in 512-bit precision,
         following the selected rounding direction.
    @notice The implementation is inspired by Remco Bloemen's
            implementation under the MIT license here:
            https://xn--2-umb.com/21/muldiv.
            Furthermore, the rounding direction design pattern is
            inspired by OpenZeppelin's implementation here:
            https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/math/Math.sol.
    @param x The 32-byte multiplicand.
    @param y The 32-byte multiplier.
    @param denominator The 32-byte divisor.
    @param roundup The Boolean variable that specifies whether
           to round up or not. The default `False` is round down.
    @return uint256 The 32-byte calculation result.
    """
    # Handle division by zero.
    assert denominator != empty(uint256), "Math: mul_div division by zero"

    # 512-bit multiplication "[prod1 prod0] = x * y".
    # Compute the product "mod 2**256" and "mod 2**256 - 1".
    # Then use the Chinese Remainder theorem to reconstruct
    # the 512-bit result. The result is stored in two 256-bit
    # variables, where: "product = prod1 * 2**256 + prod0".
    mm: uint256 = uint256_mulmod(x, y, max_value(uint256))
    # The least significant 256 bits of the product.
    prod0: uint256 = unsafe_mul(x, y)
    # The most significant 256 bits of the product.
    prod1: uint256 = empty(uint256)

    if (mm < prod0):
        prod1 = unsafe_sub(unsafe_sub(mm, prod0), 1)
    else:
        prod1 = unsafe_sub(mm, prod0)

    # Handling of non-overflow cases, 256 by 256 division.
    if (prod1 == empty(uint256)):
        if (roundup and uint256_mulmod(x, y, denominator) != empty(uint256)):
            # Calculate "ceil((x * y) / denominator)". The following
            # line cannot overflow because we have the previous check
            # "(x * y) % denominator != 0", which accordingly rules out
            # the possibility of "x * y = 2**256 - 1" and `denominator == 1`.
            return unsafe_add(unsafe_div(prod0, denominator), 1)
        else:
            return unsafe_div(prod0, denominator)

    # Ensure that the result is less than 2**256. Also,
    # prevents that `denominator == 0`.
    assert denominator > prod1, "Math: mul_div overflow"

    #######################
    # 512 by 256 Division #
    #######################

    # Make division exact by subtracting the remainder
    # from "[prod1 prod0]". First, compute remainder using
    # the `uint256_mulmod` operation.
    remainder: uint256 = uint256_mulmod(x, y, denominator)

    # Second, subtract the 256-bit number from the 512-bit
    # number.
    if (remainder > prod0):
        prod1 = unsafe_sub(prod1, 1)
    prod0 = unsafe_sub(prod0, remainder)

    # Factor powers of two out of the denominator and calculate
    # the largest power of two divisor of denominator. Always `>= 1`,
    # unless the denominator is zero (which is prevented above),
    # in which case `twos` is zero. For more details, please refer to:
    # https://cs.stackexchange.com/q/138556.
    twos: uint256 = unsafe_sub(0, denominator) & denominator
    # Divide denominator by `twos`.
    denominator_div: uint256 = unsafe_div(denominator, twos)
    # Divide "[prod1 prod0]" by `twos`.
    prod0 = unsafe_div(prod0, twos)
    # Flip `twos` such that it is "2**256 / twos". If `twos` is zero,
    # it becomes one.
    twos = unsafe_add(unsafe_div(unsafe_sub(empty(uint256), twos), twos), 1)

    # Shift bits from `prod1` to `prod0`.
    prod0 |= unsafe_mul(prod1, twos)

    # Invert the denominator "mod 2**256". Since the denominator is
    # now an odd number, it has an inverse modulo 2**256, so we have:
    # "denominator * inverse = 1 mod 2**256". Calculate the inverse by
    # starting with a seed that is correct for four bits. That is,
    # "denominator * inverse = 1 mod 2**4".
    inverse: uint256 = unsafe_mul(3, denominator_div) ^ 2

    # Use Newton-Raphson iteration to improve accuracy. Thanks to Hensel's
    # lifting lemma, this also works in modular arithmetic by doubling the
    # correct bits in each step.
    inverse = unsafe_mul(inverse, unsafe_sub(2, unsafe_mul(denominator_div, inverse))) # Inverse "mod 2**8".
    inverse = unsafe_mul(inverse, unsafe_sub(2, unsafe_mul(denominator_div, inverse))) # Inverse "mod 2**16".
    inverse = unsafe_mul(inverse, unsafe_sub(2, unsafe_mul(denominator_div, inverse))) # Inverse "mod 2**32".
    inverse = unsafe_mul(inverse, unsafe_sub(2, unsafe_mul(denominator_div, inverse))) # Inverse "mod 2**64".
    inverse = unsafe_mul(inverse, unsafe_sub(2, unsafe_mul(denominator_div, inverse))) # Inverse "mod 2**128".
    inverse = unsafe_mul(inverse, unsafe_sub(2, unsafe_mul(denominator_div, inverse))) # Inverse "mod 2**256".

    # Since the division is now exact, we can divide by multiplying
    # with the modular inverse of the denominator. This returns the
    # correct result modulo 2**256. Since the preconditions guarantee
    # that the result is less than 2**256, this is the final result.
    # We do not need to calculate the high bits of the result and
    # `prod1` is no longer necessary.
    result: uint256 = unsafe_mul(prod0, inverse)

    if (roundup and uint256_mulmod(x, y, denominator) != empty(uint256)):
        # Calculate "ceil((x * y) / denominator)". The following
        # line uses intentionally checked arithmetic to prevent
        # a theoretically possible overflow.
        result += 1

    return result
```

Please include information like:

```
cli specified: `Settings(compiler_version=None, optimize=None, evm_version=None)`
Error compiling: src/oracles/AmbientOracle.vy
Traceback (most recent call last):
  File "/opt/homebrew/bin/vyper", line 8, in <module>
    sys.exit(_parse_cli_args())
             ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/cli/vyper_compile.py", line 63, in _parse_cli_args
    return _parse_args(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/cli/vyper_compile.py", line 185, in _parse_args
    compiled = compile_files(
               ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/cli/vyper_compile.py", line 321, in compile_files
    compiler_data = vyper.compile_codes(
                    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/compiler/__init__.py", line 143, in compile_codes
    exc_handler(contract_name, exc)
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/cli/vyper_compile.py", line 219, in exc_handler
    raise exception
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/compiler/__init__.py", line 140, in compile_codes
    out[contract_name][output_format] = formatter(compiler_data)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/compiler/output.py", line 262, in build_bytecode_output
    return f"0x{compiler_data.bytecode.hex()}"
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/compiler/phases.py", line 193, in bytecode
    return generate_bytecode(self.assembly, insert_compiler_metadata=insert_compiler_metadata)
                             ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/compiler/phases.py", line 184, in assembly
    return generate_assembly(self.ir_nodes, self.settings.optimize)
                             ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/compiler/phases.py", line 165, in ir_nodes
    ir, ir_runtime = self._ir_output
                     ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/compiler/phases.py", line 161, in _ir_output
    return generate_ir_nodes(self.global_ctx, self.settings.optimize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/compiler/phases.py", line 299, in generate_ir_nodes
    ir_nodes, ir_runtime = module.generate_ir_for_module(global_ctx)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/codegen/module.py", line 424, in generate_ir_for_module
    func_ir = _ir_for_internal_function(func_ast, global_ctx, False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/codegen/module.py", line 86, in _ir_for_internal_function
    return generate_ir_for_function(func_ast, *args, **kwargs).func_ir
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/codegen/function_definitions/common.py", line 137, in generate_ir_for_function
    ret: FuncIR = InternalFuncIR(generate_ir_for_internal_function(code, func_t, context))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/codegen/function_definitions/internal_function.py", line 61, in generate_ir_for_internal_function
    ["seq"] + nonreentrant_pre + [parse_body(code.body, context, ensure_terminated=True)],
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/codegen/stmt.py", line 446, in parse_body
    ir = parse_stmt(stmt, context)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/codegen/stmt.py", line 420, in parse_stmt
    return Stmt(stmt, context).ir_node
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/codegen/stmt.py", line 41, in __init__
    self.ir_node = fn()
                   ^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/codegen/stmt.py", line 68, in parse_AnnAssign
    rhs = Expr(self.stmt.value, self.context).ir_node
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/codegen/expr.py", line 80, in __init__
    self.ir_node = fn()
                   ^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/codegen/expr.py", line 663, in parse_Call
    return DISPATCH_TABLE[function_name].build_IR(self.expr, self.context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/builtins/functions.py", line 232, in build_IR
    return convert(expr, context)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/builtins/_convert.py", line 459, in convert
    arg = Expr(arg_ast, context).ir_node
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/codegen/expr.py", line 80, in __init__
    self.ir_node = fn()
                   ^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/codegen/expr.py", line 697, in parse_Call
    return external_call.ir_for_external_call(self.expr, self.context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/codegen/external_call.py", line 233, in ir_for_external_call
    _external_call_helper(contract_address, args_ir, call_kwargs, call_expr, context)
  File "/opt/homebrew/lib/python3.11/site-packages/vyper/codegen/external_call.py", line 207, in _external_call_helper
    assert use_staticcall, "typechecker missed this"
AssertionError: typechecker missed this
```

**Comment by charles-cooper** [comment]
dup of https://github.com/vyperlang/vyper/issues/3554
